import = ["/home/maettu/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
working_directory = "None"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "ComicCode Nerd Font"
style = "Bold"

[font.italic]
family = "ComicCode Nerd Font"
style = "Italic"

[font.normal]
family = "ComicCode Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 10

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "PasteSelection"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Down"
mods = "Control"

[mouse]

[scrolling]
history = 1000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Windowed"

[window.dimensions]
columns = 60
lines = 25

[window.padding]
x = 0
y = 0
