import = ["/Users/matthiasvonarx/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
working_directory = "None"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "ComicShannsMono Nerd Font"
style = "Bold"

[font.italic]
family = "ComicShannsMono Nerd Font"
style = "Italic"

[font.normal]
family = "ComicShannsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[mouse]

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "full"
startup_mode = "Windowed"

[window.dimensions]
columns = 78
lines = 40
